(in-package :af64.runtime.cognition-types)

(defun utc-now-iso ()
  (format-iso8601 (get-universal-time)))

(defun future-utc-iso (seconds)
  (format-iso8601 (+ (get-universal-time) seconds)))

(defun format-iso8601 (universal-time)
  (multiple-value-bind (second minute hour day month year)
      (decode-universal-time universal-time 0)
    (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ"
            year month day hour minute second)))

(defun %timezone-index (text)
  (loop for i from 19 below (length text)
        for ch = (char text i)
        when (or (char= ch #\+) (char= ch #\-))
          do (return i)))

(defun parse-iso8601 (text)
  (when (and text (> (length text) 0))
    (handler-case
        (multiple-value-bind (body offset-seconds)
            (cond
              ((char= (char text (1- (length text))) #\Z)
               (values (subseq text 0 (1- (length text))) 0))
              ((%timezone-index text)
               (let* ((idx (%timezone-index text))
                      (sign (if (char= (char text idx) #\-) -1 1))
                      (offset-str (subseq text idx))
                      (hour (parse-integer (subseq offset-str 1 3)))
                      (minute (parse-integer (subseq offset-str 4 6))))
                 (values (subseq text 0 idx)
                         (* sign (+ (* hour 3600) (* minute 60))))))
              (t (values text 0)))
          (declare (ignorable offset-seconds))
          (let* ((date-part (subseq body 0 10))
                 (time-part (subseq body 11))
                 (year (parse-integer (subseq date-part 0 4)))
                 (month (parse-integer (subseq date-part 5 7)))
                 (day (parse-integer (subseq date-part 8 10)))
                 (hour (parse-integer (subseq time-part 0 2)))
                 (minute (parse-integer (subseq time-part 3 5)))
                 (second-sub (subseq time-part 6))
                 (dot (position #\. second-sub))
                 (second (parse-integer (if dot (subseq second-sub 0 dot) second-sub))))
            (- (encode-universal-time second minute hour day month year 0)
               offset-seconds)))
      (error () nil))))

(defun generate-uuid ()
  (let* ((parts #(8 4 4 4 12))
         (last-index (1- (length parts))))
    (string-downcase
     (with-output-to-string (out)
       (loop for part across parts
             for idx from 0
             do (loop repeat part do
                      (write-char (digit-char (random 16) 16) out))
                (when (< idx last-index)
                  (write-char #\- out))))))

(defun clone-hash-table (table)
  (let ((copy (make-hash-table :test (hash-table-test table))))
    (maphash (lambda (k v)
               (setf (gethash k copy)
                     (if (hash-table-p v) (clone-hash-table v) v)))
             table)
    copy))

(defstruct (cognition-job
             (:constructor make-cognition-job
                 (&key agent-id tick-number kind priority requested-model-tier
                       input-context cache-key action-name
                       (cost-estimate 0)
                       (status "pending")
                       provider-name result error
                       (created-at (utc-now-iso))
                       resolved-at last-attempt-at expires-at
                       (retry-count 0)
                       (max-attempts 3)
                       (wait-ticks 0)
                       (id (generate-uuid))))))
  (id nil :type (or null string))
  (agent-id nil :type (or null string))
  (tick-number 0 :type integer)
  (kind "generic" :type string)
  (priority 0.0 :type real)
  (requested-model-tier "base" :type string)
  (input-context (make-hash-table :test #'equal))
  (cache-key "")
  (action-name "")
  (cost-estimate 0)
  (status "pending")
  (provider-name nil)
  (result nil)
  (error nil)
  (created-at (utc-now-iso))
  (resolved-at nil)
  (last-attempt-at nil)
  (expires-at nil)
  (retry-count 0)
  (max-attempts 3)
  (wait-ticks 0))

(defstruct (cognition-result
             (:constructor make-cognition-result
                 (&key job-id agent-id action-name content provider-name
                       model-used (cached nil)
                       (metadata (make-hash-table :test #'equal))
                       (created-at (utc-now-iso))))))
  (job-id nil)
  (agent-id nil)
  (action-name "")
  (content "")
  (provider-name "")
  (model-used nil)
  (cached nil)
  (metadata (make-hash-table :test #'equal))
  (created-at (utc-now-iso)))

(defun job->plist (job)
  (json-object
   :id (cognition-job-id job)
   :agent-id (cognition-job-agent-id job)
   :tick-number (cognition-job-tick-number job)
   :kind (cognition-job-kind job)
   :priority (cognition-job-priority job)
   :requested-model-tier (cognition-job-requested-model-tier job)
   :input-context (clone-hash-table (cognition-job-input-context job))
   :cache-key (cognition-job-cache-key job)
   :action-name (cognition-job-action-name job)
   :cost-estimate (cognition-job-cost-estimate job)
   :status (cognition-job-status job)
   :provider-name (cognition-job-provider-name job)
   :result (cognition-job-result job)
   :error (cognition-job-error job)
   :created-at (cognition-job-created-at job)
   :resolved-at (cognition-job-resolved-at job)
   :last-attempt-at (cognition-job-last-attempt-at job)
   :expires-at (cognition-job-expires-at job)
   :retry-count (cognition-job-retry-count job)
   :max-attempts (cognition-job-max-attempts job)
   :wait-ticks (cognition-job-wait-ticks job)))

(defun result->plist (result)
  (json-object
   :job-id (cognition-result-job-id result)
   :agent-id (cognition-result-agent-id result)
   :action-name (cognition-result-action-name result)
   :content (cognition-result-content result)
   :provider-name (cognition-result-provider-name result)
   :model-used (cognition-result-model-used result)
   :cached (cognition-result-cached result)
   :metadata (clone-hash-table (cognition-result-metadata result))
   :created-at (cognition-result-created-at result)))

(defun job-from-json (table)
  (make-cognition-job
   :id (gethash :id table)
   :agent-id (gethash :agent-id table)
   :tick-number (or (gethash :tick-number table) 0)
   :kind (gethash :kind table)
   :priority (or (gethash :priority table) 0.0)
   :requested-model-tier (gethash :requested-model-tier table)
   :input-context (or (gethash :input-context table) (make-hash-table :test #'equal))
   :cache-key (gethash :cache-key table "")
   :action-name (gethash :action-name table "")
   :cost-estimate (or (gethash :cost-estimate table) 0)
   :status (gethash :status table "pending")
   :provider-name (gethash :provider-name table)
   :result (gethash :result table)
   :error (gethash :error table)
   :created-at (gethash :created-at table (utc-now-iso))
   :resolved-at (gethash :resolved-at table)
   :last-attempt-at (gethash :last-attempt-at table)
   :expires-at (gethash :expires-at table)
   :retry-count (or (gethash :retry-count table) 0)
   :max-attempts (or (gethash :max-attempts table) 3)
   :wait-ticks (or (gethash :wait-ticks table) 0)))

(defun result-from-json (table)
  (make-cognition-result
   :job-id (gethash :job-id table)
   :agent-id (gethash :agent-id table)
   :action-name (gethash :action-name table)
   :content (gethash :content table "")
   :provider-name (gethash :provider-name table "stub")
   :model-used (gethash :model-used table)
   :cached (gethash :cached table)
   :metadata (or (gethash :metadata table) (make-hash-table :test #'equal))
   :created-at (gethash :created-at table (utc-now-iso))))
