(in-package :af64.runtime.empirical-rollups)

(defun read-jsonl (path)
  (let ((rows '()))
    (when (probe-file path)
      (with-open-file (stream path)
        (loop for line = (read-line stream nil nil)
              while line do
                (let ((trimmed (string-trim '(#\Space #\Tab #\Newline) line)))
                  (when (> (length trimmed) 0)
                    (push (parse-json trimmed) rows))))))
    (nreverse rows)))

(defun write-jsonl (path rows)
  (ensure-runtime-dir)
  (with-open-file (stream path :direction :output :if-exists :supersede :if-does-not-exist :create)
    (dolist (row rows)
      (write-string (encode-json row) stream)
      (write-char #\Newline stream))))

(defun load-tick-reports ()
  (read-jsonl (tick-reports-path)))

(defun parse-date-components (date-string)
  (values (parse-integer (subseq date-string 0 4))
          (parse-integer (subseq date-string 5 7))
          (parse-integer (subseq date-string 8 10))))

(defun leap-year-p (year)
  (or (and (zerop (mod year 400)))
      (and (zerop (mod year 4)) (not (zerop (mod year 100))))))

(defun weeks-in-year (year)
  (let ((jan1 (nth 6 (multiple-value-list (decode-universal-time (encode-universal-time 0 0 0 1 1 year 0) 0)))))
    (if (or (= jan1 3) (and (= jan1 2) (leap-year-p year))) 53 52)))

(defun iso-week-info (year month day)
  (let* ((ut (encode-universal-time 0 0 0 day month year 0))
         (decoded (multiple-value-list (decode-universal-time ut 0)))
         (weekday (+ (nth 6 decoded) 1))
         (jan1 (encode-universal-time 0 0 0 1 1 year 0))
         (ordinal (+ 1 (floor (/ (- ut jan1) 86400))))
         (week (floor (/ (+ ordinal 10 (- weekday)) 7)))
         (iso-year year))
    (cond
      ((< week 1)
       (decf iso-year)
       (setf week (weeks-in-year iso-year)))
      ((> week (weeks-in-year iso-year))
       (incf iso-year)
       (setf week 1)))
    (values iso-year week)))

(defun week-key (date-string)
  (multiple-value-bind (year month day) (parse-date-components date-string)
    (multiple-value-bind (iso-year week) (iso-week-info year month day)
      (format nil "~4,'0D-W~2,'0D" iso-year week))))

(defun month-key (date-string)
  (format nil "~a-~a" (subseq date-string 0 4) (subseq date-string 5 7)))

(defun quarter-key (date-string)
  (multiple-value-bind (year month _) (parse-date-components date-string)
    (declare (ignore _))
    (let ((quarter (+ 1 (floor (/ (- month 1) 3)))))
      (format nil "~4,'0D-Q~d" year quarter))))

(defun year-key (date-string)
  (subseq date-string 0 4))

(defun incf-hash (table key &optional (delta 1))
  (setf (gethash key table) (+ (gethash key table 0) delta)))

(defun merge-rollup-records (rows winter-field)
  (let ((counts (make-hash-table :test #'equal))
        (providers (make-hash-table :test #'equal))
        (top-actors (make-hash-table :test #'equal))
        (active (make-hash-table :test #'equal))
        (pending (make-hash-table :test #'equal))
        (winter 0)
        (energy 0))
    (dolist (row rows)
      (let* ((record (gethash :operational-record row))
             (activity (or (and record (gethash :agent-activity record)) (make-hash-table :test #'equal)))
             (usage (or (and record (gethash :provider-usage record)) (make-hash-table :test #'equal)))
             (actors (or (and record (gethash :top-actors record)) #()))
             (active-agents (or (and record (gethash :active-agents record)) #()))
             (pending-agents (or (and record (gethash :pending-agents record)) #()))
             (energy-delta (or (and record (gethash :total-energy-delta record)) 0)))
        (maphash (lambda (k v) (incf-hash counts k v)) activity)
        (maphash (lambda (k v) (incf-hash providers k v)) usage)
        (loop for actor across actors do (incf-hash top-actors (car actor) (cdr actor)))
        (loop for agent across active-agents do (setf (gethash agent active) t))
        (loop for agent across pending-agents do (setf (gethash agent pending) t))
        (when (> (gethash winter-field record 0) 0) (incf winter))
        (incf energy energy-delta)))
    (json-object
     :agent-activity (let ((table (make-hash-table :test #'equal)))
                       (maphash (lambda (k v) (setf (gethash k table) v)) counts)
                       table)
     :provider-usage (let ((table (make-hash-table :test #'equal)))
                       (maphash (lambda (k v) (setf (gethash k table) v)) providers)
                       table)
     :winter-periods winter
     :active-agents (coerce (loop for k being the hash-keys of active collect k) 'vector)
     :pending-agents (coerce (loop for k being the hash-keys of pending collect k) 'vector)
     :top-actors (let ((acc '()))
                   (maphash (lambda (k v) (push (cons k v) acc)) top-actors)
                   (coerce (subseq (sort acc #'> :key #'cdr) 0 (min 10 (length acc))) 'vector))
     :total-energy-delta energy)))

(defun build-daily-rollups (reports)
  (let ((grouped (make-hash-table :test #'equal))
        (rollups '()))
    (dolist (report reports)
      (let ((key (subseq (gethash :generated-at report) 0 10)))
        (push report (gethash key grouped (setf (gethash key grouped) '())))))
    (maphash
     (lambda (day rows)
       (let ((counts (make-hash-table :test #'equal))
             (providers (make-hash-table :test #'equal))
             (top-actors (make-hash-table :test #'equal))
             (active (make-hash-table :test #'equal))
             (pending (make-hash-table :test #'equal))
             (winter 0)
             (energy 0))
         (dolist (report rows)
           (let ((tick-counts (or (gethash :counts report) (make-hash-table :test #'equal))))
             (incf-hash counts :active (gethash :active tick-counts 0))
             (incf-hash counts :idle (gethash :idle tick-counts 0))
             (incf-hash counts :dormant (gethash :dormant tick-counts 0)))
           (when (gethash :winter-active (gethash :ecology report)) (incf winter))
           (let ((actor (or (gethash :top-actor report) "none")))
             (unless (string= actor "none") (incf-hash top-actors actor 1)))
           (dolist (summary (coerce (gethash :agent-summaries report) 'list))
             (let ((agent (gethash :agent-id summary)))
               (when (and agent (gethash :resolved-action summary))
                 (setf (gethash agent active) t))))
           (dolist (req (coerce (gethash :requests (gethash :cognition report)) 'list))
             (when (gethash :agent-id req)
               (setf (gethash (gethash :agent-id req) pending) t)
               (incf-hash counts :cognition-requests 1)))
           (dolist (resolved (coerce (gethash :resolutions (gethash :cognition report)) 'list))
             (incf-hash counts :cognition-resolutions 1)
             (incf-hash providers (gethash :provider resolved "unknown") 1)
             (when (gethash :cached resolved) (incf-hash counts :cache-hits 1)))
           (let ((metrics (or (gethash :metrics (gethash :broker report)) (make-hash-table :test #'equal))))
             (incf-hash counts :deferred (gethash :deferred metrics 0))
             (incf-hash counts :expired-jobs (gethash :expired metrics 0))
             (incf-hash counts :cache-expired (gethash :cache-expired metrics 0)))
           (dolist (entry (coerce (gethash :entries report) 'list))
             (let ((before (gethash :energy-before entry))
                   (after (gethash :energy-after entry)))
               (when (and before after) (incf energy (- after before))))))
         (push (json-object
                :date day
                :tick-count (length rows)
                :operational-record (json-object
                                     :agent-activity counts
                                     :provider-usage providers
                                     :winter-ticks winter
                                     :active-agents (coerce (loop for k being the hash-keys of active collect k) 'vector)
                                     :pending-agents (coerce (loop for k being the hash-keys of pending collect k) 'vector)
                                     :top-actors (let ((acc '()))
                                                   (maphash (lambda (k v) (push (cons k v) acc)) top-actors)
                                                   (coerce (subseq (sort acc #'> :key #'cdr) 0 (min 10 (length acc))) 'vector))
                                     :total-energy-delta energy)
                :summary-scaffold (json-object :status "unfilled"
                                               :note "Application-specific synthesis can be layered on top of this empirical record."))
               rollups)))
     grouped)
    (sort rollups #'string< :key (lambda (row) (gethash :date row))))

(defun build-higher-rollups (items key-fn winter-field label-key)
  (let ((grouped (make-hash-table :test #'equal))
        (result '()))
    (dolist (item items)
      (let ((key (funcall key-fn (gethash :date item))))
        (push item (gethash key grouped (setf (gethash key grouped) '())))))
    (maphash
     (lambda (key rows)
       (let ((merged (merge-rollup-records rows winter-field)))
         (push (json-object
                label-key key
                :source-dates (coerce (mapcar (lambda (row) (gethash :date row)) rows) 'vector)
                :operational-record (json-object
                                     :agent-activity (gethash :agent-activity merged)
                                     :provider-usage (gethash :provider-usage merged)
                                     :winter-periods (gethash :winter-periods merged)
                                     :active-agents (gethash :active-agents merged)
                                     :pending-agents (gethash :pending-agents merged)
                                     :top-actors (gethash :top-actors merged)
                                     :total-energy-delta (gethash :total-energy-delta merged))
                :summary-scaffold (json-object :status "unfilled"
                                               :note "Application-specific synthesis can be layered on top of this empirical record."))
               result)))
     grouped)
    (sort result #'string< :key (lambda (row) (gethash label-key row))))

(defun build-weekly-rollups (daily)
  (let ((grouped (make-hash-table :test #'equal)))
    (dolist (rollup daily)
      (let ((key (week-key (gethash :date rollup))))
        (push rollup (gethash key grouped (setf (gethash key grouped) '())))))
    (let ((result '()))
      (maphash
       (lambda (key rows)
         (let ((merged (merge-rollup-records rows :winter-ticks)))
           (push (json-object
                  :week key
                  :day-count (length rows)
                  :source-dates (coerce (mapcar (lambda (row) (gethash :date row)) rows) 'vector)
                  :operational-record (json-object
                                       :agent-activity (gethash :agent-activity merged)
                                       :provider-usage (gethash :provider-usage merged)
                                       :winter-days (gethash :winter-periods merged)
                                       :active-agents (gethash :active-agents merged)
                                       :pending-agents (gethash :pending-agents merged)
                                       :top-actors (gethash :top-actors merged)
                                       :total-energy-delta (gethash :total-energy-delta merged))
                  :summary-scaffold (json-object :status "unfilled"
                                                 :note "Application-specific synthesis can be layered on top of this empirical record."))
                 result)))
       grouped)
      (sort result #'string< :key (lambda (row) (gethash :week row))))))

(defun build-monthly-rollups (daily)
  (let ((grouped (make-hash-table :test #'equal)))
    (dolist (rollup daily)
      (let ((key (month-key (gethash :date rollup))))
        (push rollup (gethash key grouped (setf (gethash key grouped) '())))))
    (let ((result '()))
      (maphash
       (lambda (key rows)
         (let ((merged (merge-rollup-records rows :winter-ticks)))
           (push (json-object
                  :month key
                  :day-count (length rows)
                  :source-dates (coerce (mapcar (lambda (row) (gethash :date row)) rows) 'vector)
                  :operational-record (json-object
                                       :agent-activity (gethash :agent-activity merged)
                                       :provider-usage (gethash :provider-usage merged)
                                       :winter-days (gethash :winter-periods merged)
                                       :active-agents (gethash :active-agents merged)
                                       :pending-agents (gethash :pending-agents merged)
                                       :top-actors (gethash :top-actors merged)
                                       :total-energy-delta (gethash :total-energy-delta merged))
                  :summary-scaffold (json-object :status "unfilled"
                                                 :note "Application-specific synthesis can be layered on top of this empirical record."))
                 result)))
       grouped)
      (sort result #'string< :key (lambda (row) (gethash :month row))))))

(defun build-quarterly-rollups (monthly)
  (let ((grouped (make-hash-table :test #'equal)))
    (dolist (rollup monthly)
      (let ((key (quarter-key (format nil "~a-01" (gethash :month rollup)))))
        (push rollup (gethash key grouped (setf (gethash key grouped) '())))))
    (let ((result '()))
      (maphash
       (lambda (key rows)
         (let ((merged (merge-rollup-records rows :winter-days)))
           (push (json-object
                  :quarter key
                  :month-count (length rows)
                  :source-months (coerce (mapcar (lambda (row) (gethash :month row)) rows) 'vector)
                  :operational-record (json-object
                                       :agent-activity (gethash :agent-activity merged)
                                       :provider-usage (gethash :provider-usage merged)
                                       :winter-months (gethash :winter-periods merged)
                                       :active-agents (gethash :active-agents merged)
                                       :pending-agents (gethash :pending-agents merged)
                                       :top-actors (gethash :top-actors merged)
                                       :total-energy-delta (gethash :total-energy-delta merged))
                  :summary-scaffold (json-object :status "unfilled"
                                                 :note "Application-specific synthesis can be layered on top of this empirical record."))
                 result)))
       grouped)
      (sort result #'string< :key (lambda (row) (gethash :quarter row))))))

(defun build-yearly-rollups (quarterly)
  (let ((grouped (make-hash-table :test #'equal)))
    (dolist (rollup quarterly)
      (let ((key (subseq (gethash :quarter rollup) 0 4)))
        (push rollup (gethash key grouped (setf (gethash key grouped) '())))))
    (let ((result '()))
      (maphash
       (lambda (key rows)
         (let ((merged (merge-rollup-records rows :winter-months)))
           (push (json-object
                  :year key
                  :quarter-count (length rows)
                  :source-quarters (coerce (mapcar (lambda (row) (gethash :quarter row)) rows) 'vector)
                  :operational-record (json-object
                                       :agent-activity (gethash :agent-activity merged)
                                       :provider-usage (gethash :provider-usage merged)
                                       :winter-quarters (gethash :winter-periods merged)
                                       :active-agents (gethash :active-agents merged)
                                       :pending-agents (gethash :pending-agents merged)
                                       :top-actors (gethash :top-actors merged)
                                       :total-energy-delta (gethash :total-energy-delta merged))
                  :summary-scaffold (json-object :status "unfilled"
                                                 :note "Application-specific synthesis can be layered on top of this empirical record."))
                 result)))
       grouped)
      (sort result #'string< :key (lambda (row) (gethash :year row))))))

(defun persist-rollups (daily weekly monthly quarterly yearly)
  (write-jsonl (daily-rollups-path) daily)
  (write-jsonl (weekly-rollups-path) weekly)
  (write-jsonl (monthly-rollups-path) monthly)
  (write-jsonl (quarterly-rollups-path) quarterly)
  (write-jsonl (yearly-rollups-path) yearly)
  (labels ((post-rollups (endpoint rows)
             (dolist (row rows)
               (handler-case (api-post endpoint row)
                 (error () (return))))))
    (post-rollups "/api/rollups/daily" daily)
    (post-rollups "/api/rollups/weekly" weekly)
    (post-rollups "/api/rollups/monthly" monthly)
    (post-rollups "/api/rollups/quarterly" quarterly)
    (post-rollups "/api/rollups/yearly" yearly)))

(defun rebuild-rollups ()
  (let* ((reports (load-tick-reports))
         (daily (build-daily-rollups reports))
         (weekly (build-weekly-rollups daily))
         (monthly (build-monthly-rollups daily))
         (quarterly (build-quarterly-rollups monthly))
         (yearly (build-yearly-rollups quarterly)))
    (persist-rollups daily weekly monthly quarterly yearly)
    (json-object :daily daily :weekly weekly :monthly monthly :quarterly quarterly :yearly yearly)))
