(in-package :af64.utils.json)

(defparameter *json-null* :null)

(defun json-null ()
  *json-null*)

(defun json-true ()
  t)

(defun json-false ()
  nil)

(defun json-keyword (string)
  (let* ((sanitized (substitute #\- #\_ string))
         (up (string-upcase sanitized)))
    (intern up :keyword)))

(defun keyword->json-key (keyword)
  (string-downcase (substitute #\_ #\- (symbol-name keyword))))

(defun json-object (&rest pairs)
  (let ((table (make-hash-table :test #'equal)))
    (loop for (key value) on pairs by #'cddr
          when key
            do (setf (gethash key table) value))
    table))

(defun json-array (&rest values)
  (coerce values 'vector))

(defun parse-json (text)
  (multiple-value-bind (value _) (parse-json-value text 0)
    value))

(defun parse-json-value (text index)
  (setf index (skip-whitespace text index))
  (when (>= index (length text))
    (error "Unexpected end of JSON input"))
  (let ((char (char text index)))
    (cond
      ((char= char #\") (parse-json-string text index))
      ((char= char #\{) (parse-json-object text index))
      ((char= char #\[) (parse-json-array text index))
      ((or (char= char #\-)
           (digit-char-p char))
       (parse-json-number text index))
      ((starts-with text index "true")
       (values t (+ index 4)))
      ((starts-with text index "false")
       (values nil (+ index 5)))
      ((starts-with text index "null")
       (values *json-null* (+ index 4)))
      (t (error "Invalid JSON token at ~a" index)))))

(defun skip-whitespace (text index)
  (loop while (< index (length text))
        for ch = (char text index)
        when (member ch '(#\Space #\Tab #\Newline #\Return))
          do (incf index)
        else
          do (return index)
        finally (return index)))

(defun parse-json-string (text index)
  (let ((buffer (make-string-output-stream)))
    (incf index) ; skip opening quote
    (loop while (< index (length text))
          for ch = (char text index)
          do (cond
               ((char= ch #\")
                (incf index)
                (return-from parse-json-string (values (get-output-stream-string buffer) index)))
               ((char= ch #\\)
                (incf index)
                (when (>= index (length text))
                  (error "Invalid JSON escape"))
                (setf ch (char text index))
                (case ch
                  ((#\" #\\ #\/) (write-char ch buffer))
                  (#\b (write-char #\Backspace buffer))
                  (#\f (write-char #\Page buffer))
                  (#\n (write-char #\Newline buffer))
                  (#\r (write-char #\Return buffer))
                  (#\t (write-char #\Tab buffer))
                  (#\u
                   (multiple-value-bind (code new-index)
                       (parse-unicode-escape text (1+ index))
                     (setf index (1- new-index))
                     (write-char (code-char code) buffer)))
                  (t (error "Unknown JSON escape sequence: ~a" ch))))
               (t (write-char ch buffer)))
          do (incf index))
    (error "Unterminated JSON string")))

(defun parse-unicode-escape (text index)
  (when (> (+ index 4) (length text))
    (error "Invalid unicode escape"))
  (let ((code 0))
    (dotimes (i 4)
      (let ((ch (char text (+ index i))))
        (setf code (+ (* code 16) (hex-digit ch)))))
    (values code (+ index 4))))

(defun hex-digit (ch)
  (cond
    ((char<= #\0 ch #\9) (- (char-code ch) (char-code #\0)))
    ((char<= #\a ch #\f) (+ 10 (- (char-code ch) (char-code #\a))))
    ((char<= #\A ch #\F) (+ 10 (- (char-code ch) (char-code #\A))))
    (t (error "Invalid hex digit: ~a" ch))))

(defun parse-json-number (text index)
  (let ((start index))
    (when (char= (char text index) #\-)
      (incf index))
    (setf index (consume-digits text index))
    (when (and (< index (length text)) (char= (char text index) #\.))
      (incf index)
      (setf index (consume-digits text index)))
    (when (and (< index (length text))
               (member (char text index) '(#\e #\E)))
      (incf index)
      (when (and (< index (length text))
                 (member (char text index) '(#\+ #\-)))
        (incf index))
      (setf index (consume-digits text index)))
    (let ((number (read-from-string text nil nil :start start :end index)))
      (unless number
        (error "Invalid JSON number starting at ~a" start))
      (values number index))))

(defun consume-digits (text index)
  (loop while (and (< index (length text)) (digit-char-p (char text index)))
        do (incf index)
        finally (return index)))

(defun parse-json-array (text index)
  (incf index) ; skip [
  (setf index (skip-whitespace text index))
  (when (>= index (length text))
    (error "Unexpected end in array"))
  (if (char= (char text index) #\])
      (values #() (1+ index))
      (let ((items '()))
        (loop
          (multiple-value-bind (value next-index)
              (parse-json-value text index)
            (push value items)
            (setf index (skip-whitespace text next-index))
            (setf index (skip-whitespace text next-index))
            (cond
              ((and (< index (length text)) (char= (char text index) #\,))
               (incf index)
               (setf index (skip-whitespace text index)))
              ((and (< index (length text)) (char= (char text index) #\]))
               (incf index)
               (return-from parse-json-array (values (coerce (nreverse items) 'vector) index)))
              (t (error "Expected , or ] in array"))))))))

(defun parse-json-object (text index)
  (incf index) ; skip {
  (setf index (skip-whitespace text index))
  (let ((table (make-hash-table :test #'equal)))
    (when (and (< index (length text)) (char= (char text index) #\}))
      (return-from parse-json-object (values table (1+ index))))
    (loop
      (multiple-value-bind (key next-index)
          (parse-json-string text index)
        (setf index (skip-whitespace text next-index))
        (unless (and (< index (length text)) (char= (char text index) #\:))
          (error "Expected : after key"))
        (incf index)
        (multiple-value-bind (value value-index)
            (parse-json-value text index)
          (setf (gethash (json-keyword key) table) value)
          (setf index (skip-whitespace text value-index))
          (cond
            ((and (< index (length text)) (char= (char text index) #\,))
             (incf index)
             (setf index (skip-whitespace text index)))
            ((and (< index (length text)) (char= (char text index) #\}))
             (incf index)
             (return-from parse-json-object (values table index)))
            (t (error "Expected , or } in object"))))))))

(defun starts-with (text index expected)
  (and (<= (+ index (length expected)) (length text))
       (string= expected text :start2 index :end2 (+ index (length expected)))))

(defun encode-json (value)
  (with-output-to-string (out)
    (encode-json-into value out)))

(defun encode-json-into (value stream)
  (cond
    ((eq value *json-null*) (write-string "null" stream))
    ((eq value t) (write-string "true" stream))
    ((null value) (write-string "false" stream))
    ((stringp value) (write-json-string value stream))
    ((numberp value) (write value :stream stream))
    ((hash-table-p value) (encode-json-object value stream))
    ((vectorp value) (encode-json-array (coerce value 'list) stream))
    ((listp value) (encode-json-array value stream))
    ((keywordp value)
     (write-json-string (keyword->json-key value) stream))
    ((symbolp value)
     (write-json-string (symbol-name value) stream))
    (t (write-json-string (princ-to-string value) stream))))

(defun encode-json-object (table stream)
  (write-char #\{ stream)
  (let ((first t)
        (pairs (loop for key being the hash-keys of table collect key)))
    (dolist (key (sort pairs #'string< :key #'key->string))
      (unless first (write-string "," stream))
      (setf first nil)
      (write-json-string (key->string key) stream)
      (write-string ":" stream)
      (encode-json-into (gethash key table) stream))
    (write-char #\} stream)))

(defun encode-json-array (list stream)
  (write-char #\[ stream)
  (loop for item in list
        for index from 0
        do (when (> index 0) (write-string "," stream))
           (encode-json-into item stream))
  (write-char #\] stream))

(defun write-json-string (string stream)
  (write-char #\" stream)
  (loop for ch across string
        do (case ch
             (#\" (write-string "\\\"" stream))
             (#\\ (write-string "\\\\" stream))
             (#\Newline (write-string "\\n" stream))
             (#\Return (write-string "\\r" stream))
             (#\Tab (write-string "\\t" stream))
             (t (write-char ch stream))))
  (write-char #\" stream))

(defun key->string (key)
  (cond
    ((stringp key) key)
    ((keywordp key) (keyword->json-key key))
    (t (string-downcase (symbol-name key)))))
